spring:
  application:
    name: order-service
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  kafka:
    bootstrapServers: localhost:9092
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: event:eddamghi.order_service.event.OrderAnalyticEvent
    template:
      defaultTopic: orderAnalyticTopic
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/orderdb?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:eddamghi}
    password: ${JDBC_DATABASE_PASSWORD:eddamghi}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
server:
  port: ${PORT:9003}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true